config/routes.rb
Rhinobook::Engine.routes.draw do

    devise_for :users, class_name: "Rhinoart::User", module: :devise, 
        :controllers => { :sessions => "rhinoart/sessions", :passwords => "rhinoart/passwords"  }
        
	scope "(:locale)", locale: /ru|en/ do 
		root :to => 'books#index'

    resources :libraries do
      resources :books
    end
		resources :books do
			resources :domains
			resources :chapters
			get 'reorder_pages'
      resources :authors
		end

		resources :chapters, only: :nil do 
			resources :pages, on: :collection
		end

    resources :statuses, only: :destroy do
      post 'set_new_status/:statusable_id/:statusable_type/:locale' => 'statuses#set_new_status', on: :collection, as: :set_new_status, via: :js
    end

    resources :temp_contents, only: [:index, :create]    
	end

    #API
    namespace :api do
      scope :v1 do
        resources :temp_contents, only: [:show]
      end
    end	
end

app/models/rhinobook/domain.rb
# == Schema Information
#
# Table name: rhinobook_domains
#
#  id                 :integer          not null, primary key
#  rhinobook_books_id :integer
#  name               :string(255)
#  descr              :text(65535)
#  locale             :string(255)
#  active             :boolean          default(TRUE)
#  created_at         :datetime
#  updated_at         :datetime
#

module Rhinobook
	class Domain < ActiveRecord::Base
		belongs_to :book, :foreign_key => "rhinobook_books_id"

		validates :name, :locale, presence: true
		validates_uniqueness_of :name, scope: [:locale, :rhinobook_books_id]	
	end
end

app/controllers/rhinobook/api/base_controller.rb
module Rhinobook
  module Api
    class BaseController < ApplicationController

      before_filter :has_api_access
      before_filter :set_locale

      class InvalidAccessRightError < StandardError; end
      class InvalidApiKeyError < StandardError; end
      class InvalidParametersError < StandardError; end
      class UserNotApprovedError < StandardError; end
      class NotFoundError < StandardError; end
      class DomainNotFoundError < StandardError; end
      class InvalidEmailError < StandardError; end
      class InvalidPasswordError < StandardError; end
      class ResourceNotFoundError < StandardError; end

      rescue_from(InvalidAccessRightError) { render_error(nil, Api::ERROR_ACCESS_DENIED_USER_HAS_NO_ACCESS_RIGHT, :unauthorized) }
      rescue_from(InvalidApiKeyError){ render_error(nil, Api::ERROR_ACCESS_DENIED_INVALID_API_TOKEN, :unauthorized) }
      rescue_from(InvalidParametersError){ render_error(nil, Api::ERROR_PARAM_TYPE, :not_found) }
      rescue_from(UserNotApprovedError){ render_error(nil, Api::ERROR_ACCESS_DENIED_USER_WASNT_APPROVED, :unauthorized) }
      rescue_from(NotFoundError){ render_error(nil, Api::ERROR_CONTENT_NOT_FOUND, :not_found) }
      rescue_from(DomainNotFoundError){ render_error(nil, Api::ERROR_DOMAIN_NOT_FOUND, :unprocessable_entity) }
      rescue_from(InvalidPasswordError){ render_error(nil, Api::ERROR_PASSWORD_MISMATCH, :forbidden) }
      rescue_from(ResourceNotFoundError){ render_error(nil, Api::ERROR_RESOURCE_NOT_FOUND, :not_found) }
      rescue_from(InvalidEmailError){ render_error(nil, Api::ERROR_PASSWORD_MISMATCH, :unauthorized) }
      rescue_from(InvalidPasswordError){ render_error(nil, Api::ERROR_PASSWORD_MISMATCH, :unauthorized) }
      rescue_from(ActiveRecord::RecordNotFound){ render_error(nil, Api::ERROR_RESOURCE_NOT_FOUND, :not_found) }
      rescue_from(NoMethodError){|e| render_error(e.message, Api::ERROR_SERVER, :internal_server_error) }


      private

      def render_error(message, code, status, options = {})
        message ||= t("api_errors.#{code}")
        render json: {message: message, error_code: code}.merge!(options), status: status
      end

      def set_locale
        I18n.locale = params[:locale] || :en
      end

      def has_api_access

        # @api_user = Rhinoart::User.find_by(auth_token: params[:api_token], approved: true) if params[:api_token].present?
        #
        # raise InvalidApiKeyError.new if @api_user.nil?
        # raise UserNotApprovedError.new unless @api_user.approved
        # raise InvalidAccessRightError.new if !@api_user.has_access_to_api?
        #TODO: temporarily
        return true

      end

      def self.swagger_error_model
        swagger_model :Error do
          description "Error response"
          property :message, :string, :required, "Error Message", {defaultValue: 'Error'}
          property :error_code, :string, :required, "Error Code", {defaultValue: 'Code'}
        end
      end

    end
  end
end

app/controllers/rhinobook/api/books_controller.rb
module Rhinobook
  module Api
    class BooksController < Api::BaseController

      swagger_controller :books, "Books"


      swagger_model :Book do
        description "Book Structure"
        property :id, :integer, :required, "Book Id"
        property :name, :string, :required, "Name"
        property :descr, :string, :required, "Description"
        property :author, :string, :required, "Author"
        property :created_at, :string, :required, "Created Date"
        property :updated_at, :string, :required, "Last modified Date"
        property :image, :Image, :required, "Image"
        property :thumb_image, :Image, :required, "Thumb Image"
        property :documents_file_size, :integer, :required, "Image files size"
      end

      swagger_model :Image do
        description "Books Image"
        property :url, :string, :required, "Image Path"
        property :file_size, :integer, :required, "Image File Size"
        property :content_type, :integer, :required, "Content Type"
      end

      swagger_error_model

      swagger_api :index do
        summary "Fetches all Books items"
        param :query, :api_token, :string, :required, "Api Token"
        param_list :path, :locale, :string, :optional, "Language locale", ['en', 'ru'], :defaultValue => 'en'
        response :ok, 'Success', :Book
        response :unauthorized, nil, :Error
      end

      def index
        @books = Rhinobook::Book.all
      end

      swagger_api :show do
        summary "Fetches Book Data by Id"
        notes "Book Data"
        param :query, :api_token, :string, :required, "Api Token"
        param_list :path, :locale, :string, :optional, "Language locale", ['en', 'ru'], :defaultValue => 'en'
        param :path, :id, :integer, :required, "Book Id"
        response :unauthorized, nil, :Error
        response :not_found, nil, :Error
      end

      def show
        @book = Rhinobook::Book.includes(:chapters => [{:pages => [:images, :videos]}]).find(params[:id])
        #render json: @book.as_json(:include => {chapters: {include: {pages: {include: [:videos, :images]}}}})
      end

      swagger_api :version do
        summary "return actual version of Book by Id"
        notes "Book Version"
        param :query, :api_token, :string, :required, "Api Token"
        param_list :path, :locale, :string, :optional, "Language locale", ['en', 'ru'], :defaultValue => 'en'
        param :path, :id, :integer, :required, "Book Id"
        response :unauthorized, nil, :Error
        response :not_found, nil, :Error
      end

      def version
        @book = Rhinobook::Book.find(params[:id])
        render json: {:version => (@book.version.present? ? @book.version : '0')}
      end

    end
  end
end

app/controllers/rhinobook/api/chapters_controller.rb
module Rhinobook
  module Api
    class ChaptersController< Api::BaseController

      swagger_controller :books, "Chapters"

      swagger_model :Chapter do
        description "Chapter Structure"
        property :id, :integer, :required, "Chapter Id", :defaultValue => 5
        property :book_id, :integer, :required, "Book Id", :defaultValue => 2
        property :name, :string, :required, "Name", :defaultValue => 'Chapter Name'
        property :position, :integer, :required, "Position Number in Book", :defaultValue => 1
      end

      swagger_error_model

      swagger_api :index do
        summary "Fetches Chapters for Book"
        notes "This lists Book Chapters by book_id"
        param :query, :api_token, :string, :required, "Api Token"
        param_list :path, :locale, :string, :optional, "Language locale", ['en', 'ru'], :defaultValue => 'en'
        param :path, :book_id, :integer, :required, "Book ID"
        response :ok, 'Success', :Chapter
        response :unauthorized, nil, :Error
        response :not_found, nil, :Error
      end

      def index
        @book = Book.find params[:book_id]
        @chapters = @book.chapters
      end

      swagger_api :show do
        summary "Fetches Chapter Data by Id"
        notes "Chapter Data"
        param :query, :api_token, :string, :required, "Api Token"
        param_list :path, :locale, :string, :optional, "Language locale", ['en', 'ru'], :defaultValue => 'en'
        param :path, :id, :integer, :required, "Chapter Id"
        response :ok, 'Success', :Chapter
        response :unauthorized, nil, :Error
        response :not_found, nil, :Error
      end

      def show
        @chapter = Chapter.find(params[:id])
      end

    end
  end
end

app/controllers/rhinobook/api/documentation_controller.rb
module Rhinobook
  module Api
    class DocumentationController < ApplicationController

      before_filter :generate_docs_in_development

      def show
        render :show, :layout => false
      end

      def generate_docs_in_development
        return unless Rails.env.development?
        Swagger::Docs::Generator.write_docs(Swagger::Docs::Config.registered_apis)
      end

      def self.basic_auth_config
        @basic_auth_config = (YAML.load_file(Rails.root.join('config/basic_auth.yml')).symbolize_keys rescue nil) || {
          :name => 'api',
          :password => 'apipass'
        }
      end
      http_basic_authenticate_with self.basic_auth_config

    end
  end
end

app/controllers/rhinobook/api/pages_controller.rb
module Rhinobook
  module Api
    class PagesController < BaseController

      swagger_controller :books, "Pages"

      swagger_model :Page do
        description "Page Structure"
        property :id, :integer, :required, "Page Id", :defaultValue => 5
        property :book_id, :integer, :required, "Chapter Id", :defaultValue => 2
        property :number, :integer, :required, "Name", :defaultValue => 1
        property :content, :string, :required, "Page Content", :defaultValue => "Page Content"
        property :advice, :integer, :required, "Advice", :defaultValue => 0
        property :resume, :integer, :required, "Resume", :defaultValue => 0
      end

      swagger_error_model

      swagger_api :index do
        summary "Fetches Pages for Chapter"
        notes "This lists Chapter Pages by chapter_id"
        param :query, :api_token, :string, :required, "Api Token"
        param_list :path, :locale, :string, :optional, "Language locale", ['en', 'ru'], :defaultValue => 'en'
        param :path, :chapter_id, :integer, :required, "Chapter ID"
        response :ok, 'Success', :Page
        response :unauthorized, nil, :Error
        response :not_found, nil, :Error
      end

      def index
        @chapter = Chapter.find(params[:chapter_id])
        @pages = @chapter.pages
      end

      swagger_api :show do
        summary "Fetches Page Data by Id"
        notes "Page Data"
        param :query, :api_token, :string, :required, "Api Token"
        param_list :path, :locale, :string, :optional, "Language locale", ['en', 'ru'], :defaultValue => 'en'
        param :path, :id, :integer, :required, "Page Id"
        response :ok, 'Success', :Page
        response :unauthorized, nil, :Error
        response :not_found, nil, :Error
      end

      def show
        @page = Page.find(params[:id])
      end

    end
  end
end

app/controllers/rhinobook/api/temp_contents_controller.rb
require_dependency "rhinobook/application_controller"

module Rhinobook
	class Api::TempContentsController < ApplicationController
		caches_action :show, expires_in: 10.minutes, :cache_path => Proc.new { |c| c.params }

		def show			
			render json: TempContent.find_by(key_hash: params[:id])
		end
	end
end

app/controllers/rhinobook/api/users_controller.rb
module Rhinobook
  module Api
    class UsersController < BaseController

      skip_before_action :has_api_access, only: [:create, :authorize]
      caches_action :authorize, :show, expires_in: 60.seconds, unless_exist: true
      #skip_before_filter  :verify_authenticity_token

      swagger_controller :users, "Users"

      swagger_model :User do
        description "User Structure"
        property :id, :integer, :required, "ID", :defaultValue => 1
        property :email, :string, :required, "Email", :defaultValue => 'test@mail.com'
        property :name, :string, :required, "Name", :defaultValue => 'User Name'
      end

      swagger_model :UserWithToken do
        description "User Structure"
        property :id, :integer, :required, "ID", :defaultValue => 1
        property :email, :string, :required, "Email", :defaultValue => 'test@mail.com'
        property :name, :string, :required, "Name", :defaultValue => 'User Name'
        property :api_token, :string, :optional, "Api Token", :defaultValue => 'User Name'
      end

      swagger_model :ValidationError do
        description "Error response"
        property :message, :string, :required, "Error Message", {defaultValue: 'Error'}
        property :error_code, :string, :required, "Error Code", {defaultValue: 'Code'}
        property :errors, :hash, :required, "Error Code", {defaultValue: {email: ['error']}}
      end

      swagger_api :create do
        summary "Create new user"
        #param :query, :locale, :integer, :optional, "Language locale"
        param :form, 'user[email]', :string, :required, "Email", :defaultValue => 'test@mail.com'
        param :form, 'user[name]', :string, :required, "Name", :defaultValue => 'User Name'
        param :form, 'user[password]', :string, :required, "Password", :defaultValue => "password"
        param :form, 'user[password_confirmation]', :string, :required, "Password confirmation", :defaultValue => "password"
        response :ok, 'Success', :UserWithToken
        response :unprocessable_entity, nil, :ValidationError
      end

      def create
        @user = Rhinoart::User.new(user_params)
        @user.add_role(Rhinoart::User::API_ROLE_USER) if !@user.has_role?(Rhinoart::User::API_ROLE_USER)
        render_error(nil, Api::ERROR_USER_VALIDATION_ERROR, :unprocessable_entity, errors: @user.errors) unless @user.save
      end

      swagger_api :authorize do
        summary "Authorize user. Returns API token if user was approved"
        param_list :path, :locale, :string, :optional, "Language locale", ['en', 'ru'], :defaultValue => 'en'
        param :form, 'user[email]', :string, :required, "Email", :defaultValue => 'test@mail.com'
        param :form, 'user[password]', :string, :required, "Password", :defaultValue => "password"
        response :ok, 'Success', :User
        response :unauthorized, nil, :Error
      end

      def authorize
        @user = Rhinoart::User.find_by(email: user_params[:email], approved: true)

        raise InvalidEmailError.new if @user.nil?
        raise InvalidPasswordError.new unless @user.valid_password? user_params[:password].to_s
        raise InvalidAccessRightError.new if !@user.has_access_to_api?
        @user.reset_auth_token! if @user.auth_token.blank?

        sign_in @user
      end

      swagger_api :show do
        summary "Show user data"
        param :query, :api_token, :string, :required, "Api Token"
        param_list :path, :locale, :string, :optional, "Language locale", ['en', 'ru'], :defaultValue => 'en'
        param :path, :id, :string, :required, "User Id"
        response :ok, 'Success', :User
        response :unprocessable_entity, nil, :Error
      end

      def show
        raise InvalidAccessRightError.new if params[:id].to_i != current_user.id
        @user = Rhinoart::User.find(params[:id])
      end

      private

      def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
      rescue Exception => e
        raise InvalidParametersError.new
      end

    end
  end
end

app/controllers/rhinobook/application_controller.rb
module Rhinobook
	class ApplicationController < ActionController::Base
		# include Rhinobook::ApplicationHelper
		# helper Rhinobook::Engine.helpers

		
	end
end

app/controllers/rhinobook/authors_controller.rb
require_dependency "rhinobook/application_controller"

module Rhinobook
	class AuthorsController < BaseController
		before_action :set_book, only: [:index, :new, :create, :edit, :update, :destroy]
		before_action :set_author, only: [:edit, :update, :destroy]

		def index			
			@authors = @book.authors
		end

		def new
			@author = Author.new
		end

		def create
			@author = Author.new(author_params)
			@author.book = @book

			if @author.save
				redirect_to params[:redirect_to] || [@book, :authors]
			else
				render action: 'new'
			end			
		end

		def edit
		end

		def update
			if @author.update(author_params)
				redirect_to params[:redirect_to] || [@book, :authors]
			else
				render action: 'edit'
			end
		end

		def destroy
			@author.destroy
			redirect_to params[:redirect_to] || [@book, :authors]
		end

		private
			def set_book
				@book = Book.find params[:book_id]	
			rescue Exception => e
				render :template => 'site/not_found', :status => 404
			end

			def set_author
				@author = Author.find params[:id]	
			rescue Exception => e
				render :template => 'site/not_found', :status => 404				
			end

			def author_params
				params[:author].permit!
			end
	end
end

app/views/rhinobook/statuses/_status_info.html.haml
- exists_statuses = @status.statusable.statuses.where(locale: locale )
- exists_st_count = exists_statuses.count
- cur_status = exists_statuses.last.present? ? exists_statuses.last.status.to_i : 0
%span.small{ id: "status_#{@status.id}" }
	%b
		= "#{Rhinobook::Status::STATUSES.key(cur_status)}".humanize
		By:
	= "<nobr>#{Rhinoart::User::current.name}</nobr> At: #{l @status.created_at, format: :short}</nobr>".html_safe
	- if @status.statusable.can_edit?(@status.locale)
		= link_to status_path(@status), data: { confirm: "Are you sure?", method: :delete, remote: true }, class: 'status-del' do
			%span.icon-remove-sign{ style: "font-size: 10px; color: red;" }

app/views/rhinobook/statuses/_statuses.html.haml
- if f.object.present?
	- exists_statuses = f.object.statuses.where(locale: locale )
	- exists_st_count = exists_statuses.count
	- cur_status = exists_statuses.last.present? ? exists_statuses.last.status.to_i+1 : 0

	- status_fields = capture do  
		- if !f.object.new_record?
			- @statuses = f.object.statuses.build
			= f.fields_for :statuses, @statuses do |ff|	
				= ff.hidden_field :locale, value: locale
				= ff.label :status do 
					= link_to "Set as #{Rhinobook::Status::STATUSES.key(cur_status)}", 					
						set_new_status_statuses_path(statusable_id: f.object, statusable_type: f.object.class.name, locale: locale), 
						method: :post,
						remote: true,
						id: "set_status_#{f.object.id}_#{locale}",
						style: "#{exists_statuses.count > 2 ? 'display: none' : ''}"

	.statuses{ id: "status_cont_#{f.object.id}_#{locale}" }
		- if exists_st_count > 0	
			- exists_statuses.each_with_index do |s, i| 
				- remove_status_link = capture do
					= link_to status_path(s), title: 'Remove status', remote: true, method: :delete, data: { confirm: t('confirm_to_delete_record') }, class: 'status-del' do 
						%span.icon-remove-sign{ style: 'font-size: 10px; color: red;' }

				- if s.status.present?
					- status_text = Rhinobook::Status::STATUSES.key s.status.to_i
					- content = "<nobr>User: #{Rhinoart::User.find(s.user_id).name}</nobr><br><nobr>At: #{l s.created_at, format: :short}</nobr>"				
					%span.small{ id: "status_#{s.id}" }	
						%b				
							= "#{status_text}".humanize
							By:
						= Rhinoart::User.find(s.user_id).name
						= l s.created_at, format: :short

						- if exists_st_count == i+1
							= remove_status_link if f.object.can_edit?(locale)						


	- if f.object.can_edit?(locale)
		.status_fields= status_fields

:javascript
	$('.status-flag').click(function(){
		var form = $('form');
		form.attr('data-remote', true);
		form.submit();
	});

app/views/rhinobook/statuses/destroy.js.erb
<% if @status.errors.any? %>
	$("#errors").html('<%= escape_javascript(render("shared/flash", object: @status, :formats => [:html])) %>');
<% else %>
	$("#status_<%=@status.id%>").remove();
	<% exists_statuses = @status.statusable.statuses.where(locale: locale ) %>
	<% exists_st_count = exists_statuses.count %>
	<% cur_status = exists_statuses.last.present? ? exists_statuses.last.status.to_i+1 : 0 %>	

	

	<% if @status.pre_status.present? %>
		$('#status_<%= @status.pre_status.id %>').append('<%= link_to "<span class=\"icon-remove-sign\" style=\"font-size: 10px; color: red;\"></span>".html_safe, status_path(@status.pre_status), remote: true, method: :delete, data: { confirm: t("confirm_to_delete_record") }, class: "status-del", style: "color:red" %>');
	<% end %>		
	//location.reload();

	<% if !@status.statusable.can_edit?(@status.locale) || exists_st_count > 2 %>
		$('.status_fields #set_status_<%= @status.statusable_id %>_<%= @status.locale %>').hide(); 
	<% else %>
		$('.status_fields #set_status_<%= @status.statusable_id %>_<%= @status.locale %>').html('Set as <%= Rhinobook::Status::STATUSES.key(cur_status) %>'); 
		$('.status_fields #set_status_<%= @status.statusable_id %>_<%= @status.locale %>').show(); 
	<% end %>	
	// location.reload();
<% end %>

app/views/rhinobook/statuses/set_new_status.js.erb
$('#status_cont_<%= @status.statusable_id %>_<%= @status.locale %>').find('.status-del').remove();

$('#status_cont_<%= @status.statusable_id %>_<%= @status.locale %>').append('<%= escape_javascript(render("rhinobook/statuses/status_info", :formats => [:html])) %>');

<% exists_statuses = @status.statusable.statuses.where(locale: locale ) %>
<% exists_st_count = exists_statuses.count %>
<% cur_status = exists_statuses.last.present? ? exists_statuses.last.status.to_i+1 : 0 %>

<% if !@status.statusable.can_edit?(@status.locale) || exists_st_count > 2 %>
	$('.status_fields #set_status_<%= @status.statusable_id %>_<%= @status.locale %>').hide(); 
<% else %>
	$('.status_fields #set_status_<%= @status.statusable_id %>_<%= @status.locale %>').html('Set as <%= Rhinobook::Status::STATUSES.key(cur_status) %>'); 
	$('.status_fields #set_status_<%= @status.statusable_id %>_<%= @status.locale %>').show(); 
<% end %>
// location.reload();