config/routes.rb
Rhinobook::Engine.routes.draw do

    devise_for :users, class_name: "Rhinoart::User", module: :devise, 
        :controllers => { :sessions => "rhinoart/sessions", :passwords => "rhinoart/passwords"  }
        
	scope "(:locale)", locale: /ru|en/ do 
		root :to => 'books#index'

    resources :libraries do
      resources :books
    end
		resources :books do
			resources :domains
			resources :chapters
			get 'reorder_pages'
      resources :authors
		end

		resources :chapters, only: :nil do 
			resources :pages, on: :collection
		end

    resources :statuses, only: :destroy do
      post 'set_new_status/:statusable_id/:statusable_type/:locale' => 'statuses#set_new_status', on: :collection, as: :set_new_status, via: :js
    end

    resources :temp_contents, only: [:index, :create]    
	end

    #API
    namespace :api do
      scope :v1 do
        resources :temp_contents, only: [:show]
      end
    end	
end

app/models/rhinobook/book.rb
# == Schema Information
#
# Table name: rhinobook_books
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  slug        :string(255)      not null
#  descr       :text(65535)
#  active      :boolean          default(FALSE)
#  created_at  :datetime
#  updated_at  :datetime
#  author_name :string(255)
#  image_ru    :string(255)
#  image_en    :string(255)
#  show_name   :boolean          default(FALSE)
#  version     :string(255)
#

module Rhinobook
	class Book < Rhinoart::Base
		# has_paper_trail
		before_validation :name_to_slug

		has_many :pages, :dependent => :destroy, :foreign_key => "rhinobook_books_id"
		accepts_nested_attributes_for :pages, allow_destroy: true, reject_if: :all_blank

		has_many :chapters, ->{ order(position: :asc) }, :dependent => :destroy, :foreign_key => "rhinobook_books_id"
		accepts_nested_attributes_for :chapters, allow_destroy: true, reject_if: :all_blank

		has_many :domains, :dependent => :destroy, :foreign_key => "rhinobook_books_id"
		accepts_nested_attributes_for :domains, allow_destroy: true, reject_if: :all_blank

		has_many :authors, :dependent => :destroy,  :foreign_key => "rhinobook_books_id"
		accepts_nested_attributes_for :authors, allow_destroy: true, reject_if: :all_blank

		has_and_belongs_to_many :libraries, join_table: :rhinobook_libraries_books

		mount_uploader :image_ru, ImageUploader
		mount_uploader :image_en, ImageUploader

		validates :name, :slug, presence: true
		validates_uniqueness_of :name, :slug		

		translates :name, :descr, :author, :active, :show_name, versioning: :paper_trail
		globalize_accessors :locales => I18n.available_locales, :attributes => translated_attribute_names	

		def can_edit?
			res = true
			pages.each do |p|
				if !p.can_edit?
					res = false
					break
				end
			end

			return res
    	end

    	def author
    		authors.where(active: true).first if authors.any?
    	end

		private
			def name_to_slug
				if !self.slug.present?
					self.slug = Rhinoart::Utils.to_slug(self.name)
				else
					self.slug = Rhinoart::Utils.to_slug(self.slug)
				end
			end
	end
end

app/controllers/rhinobook/api/base_controller.rb
module Rhinobook
  module Api
    class BaseController < ApplicationController

      before_filter :has_api_access
      before_filter :set_locale

      class InvalidAccessRightError < StandardError; end
      class InvalidApiKeyError < StandardError; end
      class InvalidParametersError < StandardError; end
      class UserNotApprovedError < StandardError; end
      class NotFoundError < StandardError; end
      class DomainNotFoundError < StandardError; end
      class InvalidEmailError < StandardError; end
      class InvalidPasswordError < StandardError; end
      class ResourceNotFoundError < StandardError; end

      rescue_from(InvalidAccessRightError) { render_error(nil, Api::ERROR_ACCESS_DENIED_USER_HAS_NO_ACCESS_RIGHT, :unauthorized) }
      rescue_from(InvalidApiKeyError){ render_error(nil, Api::ERROR_ACCESS_DENIED_INVALID_API_TOKEN, :unauthorized) }
      rescue_from(InvalidParametersError){ render_error(nil, Api::ERROR_PARAM_TYPE, :not_found) }
      rescue_from(UserNotApprovedError){ render_error(nil, Api::ERROR_ACCESS_DENIED_USER_WASNT_APPROVED, :unauthorized) }
      rescue_from(NotFoundError){ render_error(nil, Api::ERROR_CONTENT_NOT_FOUND, :not_found) }
      rescue_from(DomainNotFoundError){ render_error(nil, Api::ERROR_DOMAIN_NOT_FOUND, :unprocessable_entity) }
      rescue_from(InvalidPasswordError){ render_error(nil, Api::ERROR_PASSWORD_MISMATCH, :forbidden) }
      rescue_from(ResourceNotFoundError){ render_error(nil, Api::ERROR_RESOURCE_NOT_FOUND, :not_found) }
      rescue_from(InvalidEmailError){ render_error(nil, Api::ERROR_PASSWORD_MISMATCH, :unauthorized) }
      rescue_from(InvalidPasswordError){ render_error(nil, Api::ERROR_PASSWORD_MISMATCH, :unauthorized) }
      rescue_from(ActiveRecord::RecordNotFound){ render_error(nil, Api::ERROR_RESOURCE_NOT_FOUND, :not_found) }
      rescue_from(NoMethodError){|e| render_error(e.message, Api::ERROR_SERVER, :internal_server_error) }


      private

      def render_error(message, code, status, options = {})
        message ||= t("api_errors.#{code}")
        render json: {message: message, error_code: code}.merge!(options), status: status
      end

      def set_locale
        I18n.locale = params[:locale] || :en
      end

      def has_api_access

        # @api_user = Rhinoart::User.find_by(auth_token: params[:api_token], approved: true) if params[:api_token].present?
        #
        # raise InvalidApiKeyError.new if @api_user.nil?
        # raise UserNotApprovedError.new unless @api_user.approved
        # raise InvalidAccessRightError.new if !@api_user.has_access_to_api?
        #TODO: temporarily
        return true

      end

      def self.swagger_error_model
        swagger_model :Error do
          description "Error response"
          property :message, :string, :required, "Error Message", {defaultValue: 'Error'}
          property :error_code, :string, :required, "Error Code", {defaultValue: 'Code'}
        end
      end

    end
  end
end

app/controllers/rhinobook/api/books_controller.rb
module Rhinobook
  module Api
    class BooksController < Api::BaseController

      swagger_controller :books, "Books"


      swagger_model :Book do
        description "Book Structure"
        property :id, :integer, :required, "Book Id"
        property :name, :string, :required, "Name"
        property :descr, :string, :required, "Description"
        property :author, :string, :required, "Author"
        property :created_at, :string, :required, "Created Date"
        property :updated_at, :string, :required, "Last modified Date"
        property :image, :Image, :required, "Image"
        property :thumb_image, :Image, :required, "Thumb Image"
        property :documents_file_size, :integer, :required, "Image files size"
      end

      swagger_model :Image do
        description "Books Image"
        property :url, :string, :required, "Image Path"
        property :file_size, :integer, :required, "Image File Size"
        property :content_type, :integer, :required, "Content Type"
      end

      swagger_error_model

      swagger_api :index do
        summary "Fetches all Books items"
        param :query, :api_token, :string, :required, "Api Token"
        param_list :path, :locale, :string, :optional, "Language locale", ['en', 'ru'], :defaultValue => 'en'
        response :ok, 'Success', :Book
        response :unauthorized, nil, :Error
      end

      def index
        @books = Rhinobook::Book.all
      end

      swagger_api :show do
        summary "Fetches Book Data by Id"
        notes "Book Data"
        param :query, :api_token, :string, :required, "Api Token"
        param_list :path, :locale, :string, :optional, "Language locale", ['en', 'ru'], :defaultValue => 'en'
        param :path, :id, :integer, :required, "Book Id"
        response :unauthorized, nil, :Error
        response :not_found, nil, :Error
      end

      def show
        @book = Rhinobook::Book.includes(:chapters => [{:pages => [:images, :videos]}]).find(params[:id])
        #render json: @book.as_json(:include => {chapters: {include: {pages: {include: [:videos, :images]}}}})
      end

      swagger_api :version do
        summary "return actual version of Book by Id"
        notes "Book Version"
        param :query, :api_token, :string, :required, "Api Token"
        param_list :path, :locale, :string, :optional, "Language locale", ['en', 'ru'], :defaultValue => 'en'
        param :path, :id, :integer, :required, "Book Id"
        response :unauthorized, nil, :Error
        response :not_found, nil, :Error
      end

      def version
        @book = Rhinobook::Book.find(params[:id])
        render json: {:version => (@book.version.present? ? @book.version : '0')}
      end

    end
  end
end

app/controllers/rhinobook/api/chapters_controller.rb
module Rhinobook
  module Api
    class ChaptersController< Api::BaseController

      swagger_controller :books, "Chapters"

      swagger_model :Chapter do
        description "Chapter Structure"
        property :id, :integer, :required, "Chapter Id", :defaultValue => 5
        property :book_id, :integer, :required, "Book Id", :defaultValue => 2
        property :name, :string, :required, "Name", :defaultValue => 'Chapter Name'
        property :position, :integer, :required, "Position Number in Book", :defaultValue => 1
      end

      swagger_error_model

      swagger_api :index do
        summary "Fetches Chapters for Book"
        notes "This lists Book Chapters by book_id"
        param :query, :api_token, :string, :required, "Api Token"
        param_list :path, :locale, :string, :optional, "Language locale", ['en', 'ru'], :defaultValue => 'en'
        param :path, :book_id, :integer, :required, "Book ID"
        response :ok, 'Success', :Chapter
        response :unauthorized, nil, :Error
        response :not_found, nil, :Error
      end

      def index
        @book = Book.find params[:book_id]
        @chapters = @book.chapters
      end

      swagger_api :show do
        summary "Fetches Chapter Data by Id"
        notes "Chapter Data"
        param :query, :api_token, :string, :required, "Api Token"
        param_list :path, :locale, :string, :optional, "Language locale", ['en', 'ru'], :defaultValue => 'en'
        param :path, :id, :integer, :required, "Chapter Id"
        response :ok, 'Success', :Chapter
        response :unauthorized, nil, :Error
        response :not_found, nil, :Error
      end

      def show
        @chapter = Chapter.find(params[:id])
      end

    end
  end
end

app/controllers/rhinobook/api/documentation_controller.rb
module Rhinobook
  module Api
    class DocumentationController < ApplicationController

      before_filter :generate_docs_in_development

      def show
        render :show, :layout => false
      end

      def generate_docs_in_development
        return unless Rails.env.development?
        Swagger::Docs::Generator.write_docs(Swagger::Docs::Config.registered_apis)
      end

      def self.basic_auth_config
        @basic_auth_config = (YAML.load_file(Rails.root.join('config/basic_auth.yml')).symbolize_keys rescue nil) || {
          :name => 'api',
          :password => 'apipass'
        }
      end
      http_basic_authenticate_with self.basic_auth_config

    end
  end
end

app/controllers/rhinobook/api/pages_controller.rb
module Rhinobook
  module Api
    class PagesController < BaseController

      swagger_controller :books, "Pages"

      swagger_model :Page do
        description "Page Structure"
        property :id, :integer, :required, "Page Id", :defaultValue => 5
        property :book_id, :integer, :required, "Chapter Id", :defaultValue => 2
        property :number, :integer, :required, "Name", :defaultValue => 1
        property :content, :string, :required, "Page Content", :defaultValue => "Page Content"
        property :advice, :integer, :required, "Advice", :defaultValue => 0
        property :resume, :integer, :required, "Resume", :defaultValue => 0
      end

      swagger_error_model

      swagger_api :index do
        summary "Fetches Pages for Chapter"
        notes "This lists Chapter Pages by chapter_id"
        param :query, :api_token, :string, :required, "Api Token"
        param_list :path, :locale, :string, :optional, "Language locale", ['en', 'ru'], :defaultValue => 'en'
        param :path, :chapter_id, :integer, :required, "Chapter ID"
        response :ok, 'Success', :Page
        response :unauthorized, nil, :Error
        response :not_found, nil, :Error
      end

      def index
        @chapter = Chapter.find(params[:chapter_id])
        @pages = @chapter.pages
      end

      swagger_api :show do
        summary "Fetches Page Data by Id"
        notes "Page Data"
        param :query, :api_token, :string, :required, "Api Token"
        param_list :path, :locale, :string, :optional, "Language locale", ['en', 'ru'], :defaultValue => 'en'
        param :path, :id, :integer, :required, "Page Id"
        response :ok, 'Success', :Page
        response :unauthorized, nil, :Error
        response :not_found, nil, :Error
      end

      def show
        @page = Page.find(params[:id])
      end

    end
  end
end

app/controllers/rhinobook/api/temp_contents_controller.rb
require_dependency "rhinobook/application_controller"

module Rhinobook
	class Api::TempContentsController < ApplicationController
		caches_action :show, expires_in: 10.minutes, :cache_path => Proc.new { |c| c.params }

		def show			
			render json: TempContent.find_by(key_hash: params[:id])
		end
	end
end

app/controllers/rhinobook/api/users_controller.rb
module Rhinobook
  module Api
    class UsersController < BaseController

      skip_before_action :has_api_access, only: [:create, :authorize]
      caches_action :authorize, :show, expires_in: 60.seconds, unless_exist: true
      #skip_before_filter  :verify_authenticity_token

      swagger_controller :users, "Users"

      swagger_model :User do
        description "User Structure"
        property :id, :integer, :required, "ID", :defaultValue => 1
        property :email, :string, :required, "Email", :defaultValue => 'test@mail.com'
        property :name, :string, :required, "Name", :defaultValue => 'User Name'
      end

      swagger_model :UserWithToken do
        description "User Structure"
        property :id, :integer, :required, "ID", :defaultValue => 1
        property :email, :string, :required, "Email", :defaultValue => 'test@mail.com'
        property :name, :string, :required, "Name", :defaultValue => 'User Name'
        property :api_token, :string, :optional, "Api Token", :defaultValue => 'User Name'
      end

      swagger_model :ValidationError do
        description "Error response"
        property :message, :string, :required, "Error Message", {defaultValue: 'Error'}
        property :error_code, :string, :required, "Error Code", {defaultValue: 'Code'}
        property :errors, :hash, :required, "Error Code", {defaultValue: {email: ['error']}}
      end

      swagger_api :create do
        summary "Create new user"
        #param :query, :locale, :integer, :optional, "Language locale"
        param :form, 'user[email]', :string, :required, "Email", :defaultValue => 'test@mail.com'
        param :form, 'user[name]', :string, :required, "Name", :defaultValue => 'User Name'
        param :form, 'user[password]', :string, :required, "Password", :defaultValue => "password"
        param :form, 'user[password_confirmation]', :string, :required, "Password confirmation", :defaultValue => "password"
        response :ok, 'Success', :UserWithToken
        response :unprocessable_entity, nil, :ValidationError
      end

      def create
        @user = Rhinoart::User.new(user_params)
        @user.add_role(Rhinoart::User::API_ROLE_USER) if !@user.has_role?(Rhinoart::User::API_ROLE_USER)
        render_error(nil, Api::ERROR_USER_VALIDATION_ERROR, :unprocessable_entity, errors: @user.errors) unless @user.save
      end

      swagger_api :authorize do
        summary "Authorize user. Returns API token if user was approved"
        param_list :path, :locale, :string, :optional, "Language locale", ['en', 'ru'], :defaultValue => 'en'
        param :form, 'user[email]', :string, :required, "Email", :defaultValue => 'test@mail.com'
        param :form, 'user[password]', :string, :required, "Password", :defaultValue => "password"
        response :ok, 'Success', :User
        response :unauthorized, nil, :Error
      end

      def authorize
        @user = Rhinoart::User.find_by(email: user_params[:email], approved: true)

        raise InvalidEmailError.new if @user.nil?
        raise InvalidPasswordError.new unless @user.valid_password? user_params[:password].to_s
        raise InvalidAccessRightError.new if !@user.has_access_to_api?
        @user.reset_auth_token! if @user.auth_token.blank?

        sign_in @user
      end

      swagger_api :show do
        summary "Show user data"
        param :query, :api_token, :string, :required, "Api Token"
        param_list :path, :locale, :string, :optional, "Language locale", ['en', 'ru'], :defaultValue => 'en'
        param :path, :id, :string, :required, "User Id"
        response :ok, 'Success', :User
        response :unprocessable_entity, nil, :Error
      end

      def show
        raise InvalidAccessRightError.new if params[:id].to_i != current_user.id
        @user = Rhinoart::User.find(params[:id])
      end

      private

      def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
      rescue Exception => e
        raise InvalidParametersError.new
      end

    end
  end
end

app/views/rhinobook/books/_form.html.haml
- av_locales = (current_user.present? && current_user.locales.present? && current_user.locales.count > 0) ? current_user.locales : I18n.available_locales

= form_for(@book) do |f| 
  - if f.object.new_record?
    %legend= t(:book)
  - else
    %legend= "#{t(:book)}: \"#{@book.name}\""
  = render 'shared/error_messages', object: f.object

  .row-fluid
    .span8
      = f.label :slug, class: 'control-label'
      .controls
        = f.text_field :slug, class: 'span12'

    .span4
      = f.label :libraries, class: 'control-label'
      .controls
        = f.select :library_ids, Rhinobook::Library.all.map{|l| [l.name, l.id]}, {include_blank: true}, { multiple: true, class: 'span12 select2' }

  .row-fluid
    - av_locales.each do |locale| 
      - I18n.locale = locale      
      %div{ class: "span#{12/av_locales.count}"}
        %legend= locale

        .row-fluid
          .span10
            .control-group
              = f.label :author, class: 'control-label'
              .controls
                - autor_val = @book.author.present? ? @book.author.name : ''
                = text_field_tag :author, autor_val, class: 'span9', disabled: true
                = link_to 'Set Author', book_authors_path(@book, redirect_to: request.fullpath), class: 'btn', style: 'position: absolute;' if !f.object.new_record?
          .span2
            = f.label :active, class: 'control-label'
            .controls
              = f.check_box "active_#{locale}"

        .row-fluid
          .span10
            .control-group
              = f.label :name, class: 'control-label'
              .controls
                = f.text_field "name_#{locale}", class: 'span11' 
          .span2
            = f.label :show_name, class: 'control-label'
            .controls
              = f.check_box "show_name_#{locale}"

        .control-group
          = f.label :descr, class: 'control-label'
          .controls
            = f.text_area "descr_#{locale}", class: 'span11' 
        %small= render 'rhinobook/shared/changed_by', f: f
        %br
        %br
            

  .row-fluid
    .span6
      - if f.object.image_ru.present?
        .book-cover
          = image_tag f.object.image_ru.thumb.url
          %a{href: "#", data: {behavior: "remove_image", remove_html: f.hidden_field(:remove_image_ru, value: true)}} 
            %span.halflings-icon.remove
      - else
        = f.file_field :image_ru  

    .span6
      - if f.object.image_en.present?
        .book-cover
          = image_tag f.object.image_en.thumb.url
          %a{href: "#", data: {behavior: "remove_image", remove_html: f.hidden_field(:remove_image_en, value: true)}} 
            %span.halflings-icon.remove
      - else
        = f.file_field :image_en  


  .form-actions
    .btn-overlay
      = f.button t("_BTN_SAVE"), class: "btn btn-primary"
      = f.button t('_BTN_SAVE_AND_CONTINUE'), class: 'btn btn-success', name: 'continue', value: 'continue'
      = link_to t("_BTN_CANCEL"), books_path, class: "btn" 

- content_for :javascript do
  :javascript
    $(document).on("click", "[data-behavior*=remove_image]", function(e) {
      e.preventDefault()
      
        $(this).parent().parent().append($(this).data("remove-html"))
        $(this).parent().remove() 
    });   
  :css
    .book-cover {
      position: relative;
    }
    .book-cover a {
      display: block;
      width: 14px;
      height: 17px;
      position: absolute;
      bottom: 0;
      background-color: gray;
    }   

app/views/rhinobook/books/edit.html.haml
- provide(:title, t(:_EDIT)) 

= render 'form'

app/views/rhinobook/books/index.html.haml
- provide(:title, t(:_BOOKS))

.box-header
	%h2
		%i.fa-icon-book.align-justify
		%span.break
		= t(:_BOOKS)


.box-content
	.dataTables_wrapper
		.row-fluid
			.btn-overlay
				= link_to new_book_path, class: 'btn btn-primary' do 
					%i.halflings-icon.plus
					= t(:_BTN_CREATE)

				= link_to libraries_path, class: 'btn btn-primary' do 
					%i.fa-icon-book
					= t(:libraries)



	%table.table.table-striped.tree
		%thead
			%tr
				%th{ width: "80%" }= t(:_BOOKS) 
				%th= t(:_ACTIONS) 
		%tbody
			- if @books.any?
				- @books.each do |item| 
					%tr
						%td= link_to item.name, book_chapters_path(item)
						%td
							= link_to edit_book_path(item), class: 'btn btn-danger btn-small' do
								%i.icon-edit
							= link_to book_authors_path(item), class: 'btn btn-danger btn-small' do
								%i.icon-user
							= link_to book_domains_path(item), class: 'btn btn-danger btn-small', title: t('domains') do
								%i.icon-share
							= link_to book_reorder_pages_path(item), class: 'btn btn-danger btn-small', title: 'Reorder pages' do
								%i.icon-repeat
							- if item.can_edit?
								= link_to book_path(item), method: 'delete', class: 'btn btn-danger btn-small', data: { confirm: t('_DELETE_CONFIRM') } do
									%i.icon-trash

app/views/rhinobook/books/new.html.haml
- provide(:title, t(:_NEW_PAGE)) 

= render 'form'